# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'restaurantapp-ios-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for restaurantapp-ios-app
  pod 'Firebase/Analytics'
end
